language: cpp
sudo: required
dist: trusty

compiler:
- gcc

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qt5-qmake qtbase5-dev
- sudo apt-get install -qq libqt5script5 libqt5scripttools5 libqt5test5
- sudo apt-get install -qq qt5-default qttools5-dev-tools
- sudo apt-get install -qq libssl-dev
- qmake ChecksumJack.pro
- make
- sudo make install

script:
- ./build_unittest/tst_unittest
